services:
  app:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fL", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - database:/database
    restart: unless-stopped
    networks:
      - backend

  
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    ports:
      - 8001:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    init: true
    networks:
      - backend


volumes:
  database:


networks:
  backend:
    driver: bridge